name: Visual Tests

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  compare-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/visual-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        id: run-playwright-tests
        run: |
          # TODO: get dynamically from config
          export DOMAIN1='main--vg-volvotrucks-us--hlxsites.hlx.live' 
          export DOMAIN2='${{ github.head_ref }}-vg-volvotrucks-us--hlxsites.hlx.live'
          npx playwright test | tee playwright.log
          
          diffs=$(grep "$DOMAIN2" playwright.log)
          if [ -z "$diffs" ]; then
            echo "No diffs found"
            echo "No diffs found" >> $GITHUB_STEP_SUMMARY
          else
            echo "Diffs found"
            echo "$diffs"
          
            SUMMARY=$(cat << EOF
          ### Visual differences found: 
            $diffs
          EOF
          )
          
            echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
          
            # using multi-line-vars from  https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "SUMMARY<<$EOF" >> "$GITHUB_OUTPUT"
            echo "$SUMMARY" "$GITHUB_OUTPUT"
            echo "$EOF" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          #        name: playwright-report
          path: .github/visual-tests/screenshots/*

      - name: Comment on Pull Request
        if: ${{ steps.run-playwright-tests.outputs.SUMMARY }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            ## Validation Results
            
            ```
            ${{ steps.run-playwright-tests.outputs.SUMMARY }}
            ```
            
            ### Workflow Execution Details
            [View the workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

#        edit-mode: replace
#        comment-id: ${{ steps.find-comment.outputs.comment-id }}
