name: React to Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  process_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform custom action
        run: |
          echo "Perform your custom action here."
