name: Post Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Post comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COMMENT="- [ ] Your custom comment text here."
          
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          COMMENT_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"

          curl \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$PR_COMMENT\"}" \
            "$COMMENT_URL"
