name: Post Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '- [ ] 👋 Thanks for reporting!'
            })
